http:
  host: "0.0.0.0"
  port: "8081"
  basepath: "/api"
  
api:
  id: "17880265"
  flowName: "x-ww-platform-main"
  
s:
  shoppingcart:
    host: "s-shopping-cart-dev.us-e2.cloudhub.io"
    port: "80"
    basepath: "/api"